version: '3.0'

services:

  redis:
    image: redis:4
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=password
    ports:
      - 16379:8081
